[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
amoy = "${POLY}"

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 128
fail_on_revert = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
